@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

participant "AutoTradingUsecase" as autoTradingUsecase
participant "AutoTradingAlgorithm" as autoTradingAlgorithm
participant "TradingUsecase" as tradingUsecase
participant "EventStream" as eventStream


group AutoTradingUsecase.Start
    eventStream -> autoTradingUsecase : Send event via eventCh(Read)
    activate autoTradingUsecase
    autoTradingUsecase -> autoTradingUsecase: HandleEvent
    autoTradingUsecase -> autoTradingAlgorithm : GenerateSignal
    activate autoTradingAlgorithm
    autoTradingAlgorithm --> autoTradingUsecase : Signal
    deactivate autoTradingAlgorithm
    autoTradingUsecase -> autoTradingAlgorithm : CalculatePosition
    activate autoTradingAlgorithm
    autoTradingAlgorithm --> autoTradingUsecase : Position
    deactivate autoTradingAlgorithm
    autoTradingUsecase -> tradingUsecase : PlaceOrder (if signal indicates trade)
    activate tradingUsecase
    tradingUsecase --> autoTradingUsecase
    deactivate tradingUsecase
    deactivate autoTradingUsecase
end

group AutoTradingUsecase.Stop

end
@enduml
