@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

actor User
participant "http.Server" as httpServer
participant "TradingHandler" as tradingHandler
participant "TradingUsecase" as tradingUsecase

User -> httpServer : Send trade request
activate httpServer
httpServer -> tradingHandler : HandleTrade
activate tradingHandler
tradingHandler -> tradingHandler : Decode request body
tradingHandler -> tradingHandler : Validate order request
tradingHandler -> tradingUsecase : PlaceOrder
activate tradingUsecase
tradingUsecase --> tradingHandler : Placed order or error
deactivate tradingUsecase
tradingHandler -> tradingHandler : Create response
tradingHandler --> httpServer : Respond to user
deactivate tradingHandler
httpServer --> User : Trade response
deactivate httpServer
@enduml