@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

participant "TradingUsecase" as tradingUsecase
participant "TachibanaClient" as tachibanaClient
participant "OrderRepository" as orderRepo
participant "EventStream" as eventStream
participant "AutoTradingUsecase" as autoTradingUsecase


group PlaceOrder
    tradingUsecase -> tachibanaClient : GetSystemStatus
    activate tachibanaClient
    tachibanaClient --> tradingUsecase : System status
    deactivate tachibanaClient
    tradingUsecase -> tachibanaClient : GetIssueMaster
    activate tachibanaClient
    tachibanaClient --> tradingUsecase : Issue master data
    deactivate tachibanaClient
    tradingUsecase -> tachibanaClient : CheckPriceIsValid
    activate tachibanaClient
    tachibanaClient --> tradingUsecase : Price validity
    deactivate tachibanaClient
    tradingUsecase -> tachibanaClient : PlaceOrder
    activate tachibanaClient
    tachibanaClient --> tradingUsecase : Placed order
    deactivate tachibanaClient
    tradingUsecase -> orderRepo : CreateOrder
    activate orderRepo
    orderRepo --> tradingUsecase
    deactivate orderRepo
end

group GetOrderStatus
    tradingUsecase -> tachibanaClient : GetOrderStatus
    activate tachibanaClient
    tachibanaClient --> tradingUsecase : Order status
    deactivate tachibanaClient
end

group CancelOrder
  tradingUsecase -> tachibanaClient : CancelOrder
    activate tachibanaClient
    tachibanaClient --> tradingUsecase
    deactivate tachibanaClient
end

group HandleOrderEvent
    eventStream -> tradingUsecase : Send event via eventCh
    activate tradingUsecase
    tradingUsecase -> tradingUsecase : Process event
    tradingUsecase -> orderRepo : UpdateOrderStatus (if EC event)
    activate orderRepo
    orderRepo --> tradingUsecase
    deactivate orderRepo
    deactivate tradingUsecase
end

group Interaction with AutoTradingUsecase
    tradingUsecase -> autoTradingUsecase: Send event via eventCh(Write)
    activate autoTradingUsecase
    autoTradingUsecase --> tradingUsecase
    deactivate autoTradingUsecase
end
@enduml